# Generated by Django 4.2.9 on 2024-01-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("alumnos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo_clase", models.CharField(max_length=50)),
                ("profesor", models.CharField(max_length=50)),
                (
                    "alumnos",
                    models.ManyToManyField(
                        blank=True, related_name="clases_rel", to="alumnos.alumno"
                    ),
                ),
            ],
        ),
    ]
