# Generated by Django 4.2.9 on 2024-01-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("primer_apellido", models.CharField(max_length=100)),
                ("segundo_apellido", models.CharField(max_length=100)),
                ("sexo", models.CharField(max_length=1)),
                ("genero", models.JSONField()),
                ("fecha_nacimiento", models.CharField(max_length=15)),
                ("edad", models.IntegerField()),
                ("curp", models.CharField(max_length=18, unique=True)),
                ("descripcion", models.CharField(max_length=400)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="../src/alumnos/"
                    ),
                ),
            ],
        ),
    ]
