# Generated by Django 4.2.9 on 2024-02-04 05:41

import alumnos.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alumnos", "0003_remove_alumno_genero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to=alumnos.models.custom_upload_to
            ),
        ),
    ]
